### ISSUE TITLE
getting syntax error

### ISSUE THREAD

**Issue by petroanveshak** [metebalci/pdftitle#16]
![image](https://user-images.githubusercontent.com/62990987/96668535-f6640a80-138d-11eb-8728-6cd3c81f0103.png)

pls advise why I could be getting this syntax error

**Comment by metebalci** [comment]
pdftitle is a program that can be executed from the shell. If you would like to use it like a module/library, you can use for example get_title_from_file method.

**Comment by petroanveshak** [comment]
thank u
