### ISSUE TITLE
Get title from bytes

### ISSUE THREAD

**Issue by impredicative** [metebalci/pdftitle#2]
Currently, the `get_title` function allows getting the title from a path to a file. I'd like to be able to get the title from a `bytes` object instead. It should be easy to allow the code to also do this. Currently I'm having to create my own modified `get_title` function, duplicating most of its functionality, and this is too hacky. Thanks.

**Comment by metebalci** [comment]
Done with version 0.2 . get_title_from_io can be used, bytes can be wrapped into a BytesIO. not tested.
