### ISSUE TITLE
Read titles for every page and populate in a table or list

### ISSUE THREAD

**Issue by Mtaly** [metebalci/pdftitle#22]
Hi, I was looking for some algorithms to read the pdf title and I came across your project which is doing the job perfectly for the first page.

Could you please add some arguments that select a specific page or extract the whole pdf pages in form of a table or list?

Thanks

**Comment by metebalci** [comment]
Hello. To be able to say the page number is a good idea, I will check that.

**Comment by metebalci** [comment]
fixed in v0.11
