### ISSUE TITLE
Title from incomplete file

### ISSUE THREAD

**Issue by impredicative** [metebalci/pdftitle#3]
Is it somehow possible to get a title from an incomplete file? This currently doesn't work. I assume the title is toward the top of a file, so an entire file shouldn't really be necessary. This will prevent needless full downloads of large files.

**Comment by metebalci** [comment]
It only uses the first page, but I am not sure if whole file (always or sometimes) need to be traversed for this. You can test it I think.

**Comment by metebalci** [comment]
While trying something else, I saw pdfminer is using seek, so it may not be possible to use streaming data or at least not easily.
