### ISSUE TITLE
Can't set parameters from API

### ISSUE THREAD

**Issue by dwahdany** [metebalci/pdftitle#33]
I might have overlooked something, but it seems there is no way to adjust the parameters from API calls, e.g. you can't call `get_title_from_file(path, algo='max2')`.

**Comment by metebalci** [comment]
I didnt plan pdftitle to be embedded or used as a library, it is a command line utility, so none of such uses are considered. However, it seems there is an interest in this but I probably have to change more things.

**Comment by metebalci** [comment]
fixed by changing the signatures of `get_title_from_file` and `get_title_from_io` functions
