### ISSUE TITLE
Give suggestion to use `--replace-missing-char` in the error message?

### ISSUE THREAD

**Issue by user202729** [metebalci/pdftitle#37]
I think this would help the user to discover the option. Currently the error message just say "PDF contains a unicode char that does not exist in the font", maybe add "or pass `--replace-missing-char=" "` to forcefully ignore this error" there.

Alternatively, it's also possible to replace it with some dummy character, then if the extracted title does not contain any dummy character then silently ignore the error, since there's no harm.

Making replace-missing-char the default is also an option, but I think it's a conscious design choice to not make it so. In my case, can be I'd overwhelmingly want to use that option however.

**Comment by metebalci** [comment]
The first recommendation is definitely a good idea. I will change the text of the error to recommend using this option. Thanks for this idea.

Like you said, I do not want to do this by default although it is probably how many would use the tool.

**Comment by metebalci** [comment]
fixed by changing the error message
