### ISSUE TITLE
Break up digraph?

### ISSUE THREAD

**Issue by user202729** [metebalci/pdftitle#38]
Currently, the program may output digraph for certain PDFs.

For example https://arxiv.org/pdf/1506.02640.pdf .

```bash
$ pdftitle -p 1506.02640.pdf 
You Only Look Once: Uniﬁed, Real-Time Object Detection
```
Note the `ﬁ` in `Uniﬁed`.

I think it may be preferable to break it up by default?

**Comment by metebalci** [comment]
As expected, this is how it is saved in the PDF, but I do get the point and for a tool like pdftitle which outputs a text, I think it makes sense. I am not sure yet how easy would be to implement this but I guess the best would be to have this behavior (convert the ligature glyph to the individual glyphs) by default and have an option to disable this feature (as it works now).

**Comment by metebalci** [comment]
This may not cover all the cases but I have implemented the conversion of latin ligatures (ff, fi, fl, ffl, ft, st) to individual characters in 0.12 by default. This behavior can be disabled with `--do-not-convert-ligatures`. I have tested with the mentioned pdf.

```
$ pdftitle -p 1506.02640
You Only Look Once: Unified, Real-Time Object Detection

$ pdftitle -p 1506.02640 --do-not-convert-ligatures
You Only Look Once: Uniﬁed, Real-Time Object Detection
```

**Comment by user202729** [comment]
Great!

(did you forget to push the code?)

Side note, I guess you can normalize like https://stackoverflow.com/a/9175406/5267751 . Not sure if it has any side effect though (in the latter case just stick with manual loop table).

**Comment by metebalci** [comment]
I converted them manually for the moment, I need to know more about unicode to use something like that.
