### ISSUE TITLE
It doesn't work with python 3.11

### ISSUE THREAD

**Issue by zoharl3** [metebalci/pdftitle#44]
`pdftitle` gives an error

```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pdftitle\pdftitle.py", line 24, in <module>
    from .constants import ALGO_ORIGINAL, ALGO_MAX2, ALGO_ELIOT
ImportError: attempted relative import with no known parent package
```
If I remove the dot from all the imports, it runs but does nothing.

**Comment by metebalci** [comment]
Is this the latest version of pdftitle ? I cannot reproduce the error with Python 3.10 and 3.12. Can you reinstall pdftitle ?

**Comment by zoharl3** [comment]
Up until today, an old version of pdftitle worked fine on python 3.7.8.

Today, I upgraded to Python 3.11.9, and pip installed pdftitle twice.

**Comment by metebalci** [comment]
I still cannot reproduce it on Windows using Python 3.11. 9

```
D:\projects\PYTHON>d:\Python\Python311\python.exe -m pip install pdftitle
...

D:\projects\PYTHON>d:\Python\Python311\Scripts\pdftitle.exe -p pdftitle\cli_tests\knuth65.pdf
On the Translation of Languages from Left to Right

D:\projects\PYTHON>d:\Python\Python311\python.exe --version
Python 3.11.9
```

**Comment by zoharl3** [comment]
Sorry, my bad. There seems to be a lot of versions of pdftitle.py, and I don't know where mine is from:

https://drive.google.com/file/d/14rgLH0yVCCMrR3gewkOrVhnMMV22QwpM/view?pli=1

I tweaked it a bit, and it works fine now.

Yours works on knuth65.pdf while the other one doesn't. On the other hand, yours doesn't work on most of my papers, e.g.,

http://dilbert.engr.ucdavis.edu/~suku/nem/papers/nem_polyreview.pdf

I haven't looked into the algorithms and such, and maybe I'll look at this more in depth in the future.

(By the way, yours suddenly started working without errors--and no modifications. Then, I installed the dependencies of the other one, and yours stopped working again--different errors that I haven't looked into.)

**Comment by metebalci** [comment]
> https://drive.google.com/file/d/14rgLH0yVCCMrR3gewkOrVhnMMV22QwpM/view?pli=1

I dont know what is this code, it is not mine, not from this project. The way to install pdftitle is always `pip install pdftitle`. Also, it is better to create a virtual environment first to isolate the installation.
