### ISSUE TITLE
[Feature request] author name and title

### ISSUE THREAD

**Issue by kirk86** [metebalci/pdftitle#8]
Hi and thanks for this pkg. 
I was wondering whether it would have been feasible to add the ability to extract the author last name and title as well? For instance give a pdf file to ouput sth like `authorLastNameYear_Title`?

**Comment by metebalci** [comment]
I think it can be done for certain cases, but I guess it would generally have more errors/mistakes than title.

**Comment by metebalci** [comment]
Closing this issue, assuming that is not going to be implemented.
